---
- name: Update and upgrade apt packages on VMs
  hosts: all
  become: yes  # Ensures the tasks run with sudo privileges
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes