    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker repository with trusted option
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=amd64 trusted=yes] https://download.docker.com/linux/ubuntu mantic stable"
        create: yes

    - name: Update apt package index after adding Docker repository
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker CE, CLI, and containerd
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Download Docker Compose v2 binary using curl
      ansible.builtin.command:
        cmd: "curl -fsSL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose"
      args:
        warn: false

    - name: Set execute permissions for Docker Compose
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Create symbolic link for Docker Compose v2
      ansible.builtin.file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link

    - name: Verify Docker installation
      ansible.builtin.command:
        cmd: docker --version
      register: docker_version_output

    - name: Verify Docker Compose installation
      ansible.builtin.command:
        cmd: docker-compose --version
      register: docker_compose_version_output

    - name: Debug Docker version
      ansible.builtin.debug:
        var: docker_version_output.stdout

    - name: Debug Docker Compose version
      ansible.builtin.debug:
        var: docker_compose_version_output.stdout
