    - name: Add SSH Key to the ansible User on the VM
      ansible.builtin.shell: |
        mkdir -p /home/ansible/.ssh
        echo "{{ sshkey }}" >> /home/ansible/.ssh/authorized_keys
        chown -R ansible:ansible /home/ansible/.ssh
        chmod 700 /home/ansible/.ssh
        chmod 600 /home/ansible/.ssh/authorized_keys
      vars:
        ansible_ssh_user: "{{ ansibleUser_name }}"
        ansible_ssh_pass: "{{ lookup('env', 'ansibleUser_password') }}"        
        ansible_connection: ssh
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    
    - name: Set the SSH private key dynamically
      set_fact:
        ansible_ssh_private_key_file: "../key"

    - name: Revert PasswordAuthentication to 'no'
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
        regexp: '^PasswordAuthentication yes'
        line: 'PasswordAuthentication no'
        state: present
      become: true
      vars:
        ansible_ssh_user: "{{ ansibleUser_name }}"
        ansible_become_pass: "{{ lookup('env', 'ansibleUser_password') }}"
        ansible_connection: ssh
        ansible_ssh_private_key_file: "../key"
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        
    - name: Wait for apt lock to be released
      ansible.builtin.shell: |
        while fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do
          echo "Waiting for apt lock to be released..."
          sleep 2
        done
        while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "Waiting for dpkg lock to be released..."
          sleep 2
        done
      become: yes
    
    - name: Ensure software-properties-common is installed
      ansible.builtin.apt:
        name: software-properties-common
        state: present
        update_cache: yes
      become: yes
    
    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
        update_cache: yes
      become: yes
    
    - name: Enable QEMU Guest Agent
      ansible.builtin.systemd:
        name: qemu-guest-agent
        enabled: yes
        state: started
      become: yes



    - name: Restart SSH service after configuration change
      ansible.builtin.shell: |
        sudo systemctl restart ssh
      become: true
      vars:
        ansible_ssh_user: "{{ ansibleUser_name }}"
        ansible_ssh_private_key_file: "../key"
        ansible_connection: ssh
        ansible_become_pass: "{{ lookup('env', 'ansibleUser_password') }}"
        ansible_ssh_private_key_file: "../key"
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
